compute_environment: LOCAL_MACHINE
distributed_type: FSDP
mixed_precision: bf16
num_machines: 1
num_processes: 8
machine_rank: 0
main_training_function: main
rdzv_backend: static
same_network: true
fsdp_config:
  fsdp_version: 2
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen3DecoderLayer
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_offload_params: false
  fsdp_activation_checkpointing: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_reshard_after_forward: true
downcast_bf16: "no"
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
